src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: RecipeRepository::class)]
#[UniqueEntity('title')]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 2,
        max: 50,
    )]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\Positive()]
    private ?int $preparation_time = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\PositiveOrZero()]
    private ?int $timeout = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\PositiveOrZero()]
    private ?int $cooking_time = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $ingredient = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $steps = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?bool $isPremium = null;

    #[ORM\ManyToMany(targetEntity: Diet::class, inversedBy: 'recipes')]
    private Collection $diets;

    #[ORM\ManyToMany(targetEntity: Allergen::class, inversedBy: 'recipes')]
    private Collection $allergens;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: Opinion::class, orphanRemoval: true)]
    private Collection $opinions;

    private ?float $average = null;

    public function __construct()
    {
        $this->diets = new ArrayCollection();
        $this->allergens = new ArrayCollection();
        $this->opinions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparation_time;
    }

    public function setPreparationTime(int $preparation_time): static
    {
        $this->preparation_time = $preparation_time;

        return $this;
    }

    public function getTimeout(): ?int
    {
        return $this->timeout;
    }

    public function setTimeout(int $timeout): static
    {
        $this->timeout = $timeout;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->cooking_time;
    }

    public function setCookingTime(int $cooking_time): static
    {
        $this->cooking_time = $cooking_time;

        return $this;
    }

    public function getIngredient(): ?string
    {
        return $this->ingredient;
    }

    public function setIngredient(string $ingredient): static
    {
        $this->ingredient = $ingredient;

        return $this;
    }

    public function getSteps(): ?string
    {
        return $this->steps;
    }

    public function setSteps(string $steps): static
    {
        $this->steps = $steps;

        return $this;
    }

    public function isIsPremium(): ?bool
    {
        return $this->isPremium;
    }

    public function setIsPremium(bool $isPremium): static
    {
        $this->isPremium = $isPremium;

        return $this;
    }

    /**
     * @return Collection<int, Diet>
     */
    public function getDiets(): Collection
    {
        return $this->diets;
    }

    public function addDiet(Diet $diet): static
    {
        if (!$this->diets->contains($diet)) {
            $this->diets->add($diet);
        }

        return $this;
    }

    public function removeDiet(Diet $diet): static
    {
        $this->diets->removeElement($diet);

        return $this;
    }

    /**
     * @return Collection<int, Allergen>
     */
    public function getAllergens(): Collection
    {
        return $this->allergens;
    }

    public function addAllergen(Allergen $allergen): static
    {
        if (!$this->allergens->contains($allergen)) {
            $this->allergens->add($allergen);
        }

        return $this;
    }

    public function removeAllergen(Allergen $allergen): static
    {
        $this->allergens->removeElement($allergen);

        return $this;
    }

    /**
     * @return Collection<int, Opinion>
     */
    public function getOpinions(): Collection
    {
        return $this->opinions;
    }

    public function addOpinion(Opinion $opinion): static
    {
        if (!$this->opinions->contains($opinion)) {
            $this->opinions->add($opinion);
            $opinion->setRecipe($this);
        }

        return $this;
    }

    public function removeOpinion(Opinion $opinion): static
    {
        if ($this->opinions->removeElement($opinion)) {
            // set the owning side to null (unless already changed)
            if ($opinion->getRecipe() === $this) {
                $opinion->setRecipe(null);
            }
        }

        return $this;
    }

    public function getAverage()
    {
        $opinions = $this->opinions;

        if ($opinions->toArray() === []) {
            $this->average = null;
            return $this->average;
        }

        $total = 0;
        foreach ($opinions as $opinion) {
            $total += $opinion->getNote();
        }

        $this->average = $total / count($opinions);

        return $this->average;
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Opinion;
use App\Entity\Recipe;
use App\Form\OpinionType;
use App\Form\RecipeType;
use App\Repository\OpinionRepository;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Twig\Environment;

class RecipeController extends AbstractController
{
    /**
     * Display all recipes
     *
     * @param RecipeRepository $recipeRepository
     * @return Response
     */
    #[Route('/recipe', name: 'recipe', methods: ['GET'])]
    public function index(RecipeRepository $recipeRepository): Response
    {
        $recipes = $recipeRepository->findAll();

        return $this->render('recipe/index.html.twig', [
            'recipes' => $recipes
        ]);
    }

    /**
     * Display one recipe
     * Give an opinion for connected user
     * 
     * @param Recipe $recipe
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/recipe/show/{id}', name: 'recipe.show', methods: ['GET', 'POST'])]
    public function show(Recipe $recipe, Request $request, EntityManagerInterface $em, OpinionRepository $opinionRepository, Environment $environment): Response
    {
        $recipeIngredients = explode(',', $recipe->getIngredient());
        $recipeSteps = explode(';', $recipe->getSteps());

        $opinion = new Opinion();
        $opinion->setUser($this->getUser());
        $opinion->setRecipe($recipe);

        $form = $this->createForm(OpinionType::class, $opinion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $opinion = $form->getData();

            $em->persist($opinion);
            $em->flush();

            return new JsonResponse([
                'html' => $environment->render('opinion/index.html.twig', [
                    'opinion' => $opinion
                ])
            ]);
        }


        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
            'recipeIngredients' => $recipeIngredients,
            'recipeSteps' => $recipeSteps,
            'opinions' => $opinionRepository->findAll(),
            'form' => $form->createView()
        ]);
    }

    /**
     * Create a recipe
     *
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/recipe/new', name: 'recipe.new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();

            $em->persist($recipe);
            $em->flush();

            $this->addFlash(
                'success',
                'La nouvelle recette à bien été ajoutée.'
            );

            return $this->redirectToRoute('recipe');
        }

        return $this->render('recipe/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Edit a recipe
     *
     * @param Recipe $recipe
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/recipe/edit/{id}', name: 'recipe.edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Recipe $recipe, Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();

            $em->persist($recipe);
            $em->flush();

            $this->addFlash(
                'success',
                'La recette à bien été modifiée.'
            );

            return $this->redirectToRoute('recipe');
        }

        return $this->render('recipe/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Delete a recipe
     *
     * @param Recipe $recipe
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/recipe/delete/{id}', name: 'recipe.delete', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Recipe $recipe, EntityManagerInterface $em): Response
    {
        $em->remove($recipe);
        $em->flush();

        $this->addFlash(
            'success',
            'La recette à bien été supprimée.'
        );

        return $this->redirectToRoute('recipe');
    }

    /**
     * Delete an opinion
     *
     * @param Opinion $recipe
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/opinion/delete/{id}', name: 'opinion.delete', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function deleteOpinion(Opinion $opinion, EntityManagerInterface $em): Response
    {
        $em->remove($opinion);
        $em->flush();

        $this->addFlash(
            'success',
            'L\'avis à bien été supprimé.'
        );

        return $this->redirectToRoute('recipe');
    }
}

templates/recipe/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}SC Diet & Nutri - Modifier une recette{% endblock %}

{% block body %}
<div class="container">
  <h1 class="display-3 mt-3">Modifier une recette</h1>
  {{ form_start(form) }}
  <div class="form-group">
    {{ form_label(form.title) }}
    {{ form_widget(form.title) }}
    <div class="form-error">
      {{ form_errors(form.title) }}
    </div>
  </div>
  <div class="form-group">
    {{ form_label(form.description) }}
    {{ form_widget(form.description) }}
    <div class="form-error">
      {{ form_errors(form.description) }}
    </div>
  </div>
  <div class="form-group">
    {{ form_label(form.preparation_time) }}
    {{ form_widget(form.preparation_time) }}
    <div class="form-error">
      {{ form_errors(form.preparation_time) }}
    </div>
  </div>
  <div class="form-group">
    {{ form_label(form.timeout) }}
    {{ form_widget(form.timeout) }}
    <div class="form-error">
      {{ form_errors(form.timeout) }}
    </div>
  </div>
  <div class="form-group">
    {{ form_label(form.cooking_time) }}
    {{ form_widget(form.cooking_time) }}
    <div class="form-error">
      {{ form_errors(form.cooking_time) }}
    </div>
  </div>
  <div class="form-group">
    {{ form_label(form.ingredient) }}
    {{ form_widget(form.ingredient) }}
    <div class="form-error">
      {{ form_errors(form.ingredient) }}
    </div>
  </div>
  <div class="form-group">
    {{ form_label(form.steps) }}
    {{ form_widget(form.steps) }}
    <div class="form-error">
      {{ form_errors(form.steps) }}
    </div>
  </div>
  <div class="form-check form-switch mt-3">
    {{ form_label(form.isPremium) }}
    {{ form_widget(form.isPremium) }}
    <div class="form-error">
      {{ form_errors(form.isPremium) }}
    </div>
  </div>
  {{ form_row(form.diets) }}
  {{ form_row(form.allergens) }}
  <div class="form-group my-3">
    {{ form_row(form.submit) }}
  </div>
  {{ form_end(form) }}
</div>
{% endblock body %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SC Diet & Nutri - Recettes{% endblock %}

{% block body %}
<div class="container">
    <h1 class="display-3 mt-3">Recettes</h1>
    {% for message in app.flashes('success') %}
    <div class="alert alert-dismissible alert-success mt-3">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        {{ message }}
    </div>
    {% endfor %}
    {% if app.user and 'ROLE_ADMIN' in app.user.roles %}
    <a href="{{ path('recipe.new')}}" class="btn btn-outline-primary my-3"> Ajouter une nouvelle recette</a>
    {% endif %}
    {% for recipe in recipes %} {# Get all the recipes #}
    {% if app.user %} {# Check if user is logged in #}
    {% if 'ROLE_ADMIN' in app.user.roles %} {# Check if the user is admin #}
    <div class="card my-3 p-3">
        <h3 class="card-title">{{ recipe.title }}</h3>
        <h5 class="card-subtitle my-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stopwatch"
                viewBox="0 0 16 16">
                <path d="M8.5 5.6a.5.5 0 1 0-1 0v2.9h-3a.5.5 0 0 0 0 1H8a.5.5 0 0 0 .5-.5V5.6z" />
                <path
                    d="M6.5 1A.5.5 0 0 1 7 .5h2a.5.5 0 0 1 0 1v.57c1.36.196 2.594.78 3.584 1.64a.715.715 0 0 1 .012-.013l.354-.354-.354-.353a.5.5 0 0 1 .707-.708l1.414 1.415a.5.5 0 1 1-.707.707l-.353-.354-.354.354a.512.512 0 0 1-.013.012A7 7 0 1 1 7 2.071V1.5a.5.5 0 0 1-.5-.5zM8 3a6 6 0 1 0 .001 12A6 6 0 0 0 8 3z" />
            </svg>
            {{ recipe.preparationTime + recipe.timeout + recipe.cookingTime }} min
        </h5>
        <p class="card-text">{{ recipe.description }}</p>
        <p class="card-text">
            <a href="{{ path('recipe.show', {id: recipe.id}) }}" class="ml-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-eye text-primary" viewBox="0 0 16 16">
                    <path
                        d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                </svg>
            </a>
            <a href="{{ path('recipe.edit', {id: recipe.id}) }}" class="mx-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-pen text-info" viewBox="0 0 16 16">
                    <path
                        d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" />
                </svg>
            </a>
            <a href="{{ path('recipe.delete', {id: recipe.id}) }}" class="">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-trash text-secondary" viewBox="0 0 16 16">
                    <path
                        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                    <path
                        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                </svg>
            </a>
        </p>
    </div>
    {% endif %} {# End admin check #}
    {% for diet in app.user.diets %} {# Get all diets of current user #}
    {% if diet in recipe.diets %} {# Check if user's diets and recipe's diets match #}
    {% if app.user.allergens is not empty %} {# Check if user has allergen #}
    {% for allergen in app.user.allergens %} {# Get all allergers of current user #}
    {% if allergen not in recipe.allergens %} {# Check if user's allergens and recipe's allergens not match #}
    <div class="card my-3 p-3">
        <h3 class="card-title">{{ recipe.title }}</h3>
        <h5 class="card-subtitle my-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stopwatch"
                viewBox="0 0 16 16">
                <path d="M8.5 5.6a.5.5 0 1 0-1 0v2.9h-3a.5.5 0 0 0 0 1H8a.5.5 0 0 0 .5-.5V5.6z" />
                <path
                    d="M6.5 1A.5.5 0 0 1 7 .5h2a.5.5 0 0 1 0 1v.57c1.36.196 2.594.78 3.584 1.64a.715.715 0 0 1 .012-.013l.354-.354-.354-.353a.5.5 0 0 1 .707-.708l1.414 1.415a.5.5 0 1 1-.707.707l-.353-.354-.354.354a.512.512 0 0 1-.013.012A7 7 0 1 1 7 2.071V1.5a.5.5 0 0 1-.5-.5zM8 3a6 6 0 1 0 .001 12A6 6 0 0 0 8 3z" />
            </svg>
            {{ recipe.preparationTime + recipe.timeout + recipe.cookingTime }} min
        </h5>
        <p class="card-text">{{ recipe.description }}</p>
        <p class="card-text">
            <a href="{{ path('recipe.show', {id: recipe.id}) }}" class="ml-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-eye text-primary" viewBox="0 0 16 16">
                    <path
                        d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                </svg>
            </a>
        </p>
    </div>
    {% endif %} {# End allergens check #}
    {% endfor %} {# End allergens loop #}
    {% else %} {# If user doesn't have allergen #}
    <div class="card my-3 p-3">
        <h3 class="card-title">{{ recipe.title }}</h3>
        <h5 class="card-subtitle my-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stopwatch"
                viewBox="0 0 16 16">
                <path d="M8.5 5.6a.5.5 0 1 0-1 0v2.9h-3a.5.5 0 0 0 0 1H8a.5.5 0 0 0 .5-.5V5.6z" />
                <path
                    d="M6.5 1A.5.5 0 0 1 7 .5h2a.5.5 0 0 1 0 1v.57c1.36.196 2.594.78 3.584 1.64a.715.715 0 0 1 .012-.013l.354-.354-.354-.353a.5.5 0 0 1 .707-.708l1.414 1.415a.5.5 0 1 1-.707.707l-.353-.354-.354.354a.512.512 0 0 1-.013.012A7 7 0 1 1 7 2.071V1.5a.5.5 0 0 1-.5-.5zM8 3a6 6 0 1 0 .001 12A6 6 0 0 0 8 3z" />
            </svg>
            {{ recipe.preparationTime + recipe.timeout + recipe.cookingTime }} min
        </h5>
        <p class="card-text">{{ recipe.description }}</p>
        <p class="card-text">
            <a href="{{ path('recipe.show', {id: recipe.id}) }}" class="ml-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-eye text-primary" viewBox="0 0 16 16">
                    <path
                        d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                </svg>
            </a>
        </p>
    </div>
    {% endif %} {# End check if user allergen exist #}
    {% endif %} {# End diets check #}
    {% endfor %} {# End diets loop #}
    {% else %} {# If user is not logged in #}
    {% if recipe.isPremium == false %} {# Check if is not a premium recipe #}
    <div class="card my-3 p-3">
        <h3 class="card-title">{{ recipe.title }}</h3>
        <h5 class="card-subtitle my-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stopwatch"
                viewBox="0 0 16 16">
                <path d="M8.5 5.6a.5.5 0 1 0-1 0v2.9h-3a.5.5 0 0 0 0 1H8a.5.5 0 0 0 .5-.5V5.6z" />
                <path
                    d="M6.5 1A.5.5 0 0 1 7 .5h2a.5.5 0 0 1 0 1v.57c1.36.196 2.594.78 3.584 1.64a.715.715 0 0 1 .012-.013l.354-.354-.354-.353a.5.5 0 0 1 .707-.708l1.414 1.415a.5.5 0 1 1-.707.707l-.353-.354-.354.354a.512.512 0 0 1-.013.012A7 7 0 1 1 7 2.071V1.5a.5.5 0 0 1-.5-.5zM8 3a6 6 0 1 0 .001 12A6 6 0 0 0 8 3z" />
            </svg>
            {{ recipe.preparationTime + recipe.timeout + recipe.cookingTime }} min
        </h5>
        <p class="card-text">{{ recipe.description }}</p>
        <p class="card-text">
            <a href="{{ path('recipe.show', {id: recipe.id}) }}" class="ml-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-eye text-primary" viewBox="0 0 16 16">
                    <path
                        d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                </svg>
            </a>
        </p>
    </div>
    {% endif %} {# End premium check #}
    {% endif %} {# End user logged in check #}
    {% endfor %} {# End recipes loop #}
</div>
{% endblock %}